In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
colnames = ['Area', 'Rooms', 'Price']
dataset = pd.read_csv("https://raw.githubusercontent.com/nishithkotak/machine-learning/refs/heads/master/ex1data2.txt", names = colnames)

In [ ]:
dataset

    Area  Rooms   Price
0   2104      3  399900
1   1600      3  329900
2   2400      3  369000
3   1416      2  232000
4   3000      4  539900
5   1985      4  299900
6   1534      3  314900
7   1427      3  198999
8   1380      3  212000
9   1494      3  242500
10  1940      4  239999
11  2000      3  347000
12  1890      3  329999
13  4478      5  699900
14  1268      3  259900
15  2300      4  449900
16  1320      2  299900
17  1236      3  199900
18  2609      4  499998
19  3031      4  599000
20  1767      3  252900
21  1888      2  255000
22  1604      3  242900
23  1962      4  259900
24  3890      3  573900
25  1100      3  249900
26  1458      3  464500
27  2526      3  469000
28  2200      3  475000
29  2637      3  299900
30  1839      2  349900
31  1000      1  169900
32  2040      4  314900
33  3137      3  579900
34  1811      4  285900
35  1437      3  249900
36  1239      3  229900
37  2132      4  345000
38  4215      4  549000
39  2162      4  287000
40  1664      2  368500
41  2238      3  329900
42  2567      4  314000
43  1200      3  299000
44   852      2  179900
45  1852      4  299900
46  1203      3  239500

In [ ]:
dataset.describe()

              Area      Rooms          Price
count    47.000000  47.000000      47.000000
mean   2000.680851   3.170213  340412.659574
std     794.702354   0.760982  125039.899586
min     852.000000   1.000000  169900.000000
25%    1432.000000   3.000000  249900.000000
50%    1888.000000   3.000000  299900.000000
75%    2269.000000   4.000000  384450.000000
max    4478.000000   5.000000  699900.000000

In [ ]:
Area = dataset.iloc[0:dataset.shape[0], 0:1]
Rooms = dataset.iloc[0:dataset.shape[0], 1:2]
Price = dataset.iloc[0:dataset.shape[0], 2:3]

In [ ]:
dataset.shape

(47, 3)

In [ ]:
#function normalization
def feature_normalization(x):
  mean = np.mean(x, axis = 0)
  std = np.std(x, axis = 0)
  x_normalized = (x - mean)/std
  return x_normalized, mean, std

In [ ]:
data_norm = dataset.values
m = data_norm.shape[0]

#take the feature vector
x2 = data_norm[:,0:2].reshape(m,2)
x2_norm, mean, std = feature_normalization(x2)

y2 = data_norm[:,2:3].reshape(m,1)  #Output price column

In [ ]:
x2_norm

array([[ 1.31415422e-01, -2.26093368e-01],
       [-5.09640698e-01, -2.26093368e-01],
       [ 5.07908699e-01, -2.26093368e-01],
       [-7.43677059e-01, -1.55439190e+00],
       [ 1.27107075e+00,  1.10220517e+00],
       [-1.99450507e-02,  1.10220517e+00],
       [-5.93588523e-01, -2.26093368e-01],
       [-7.29685755e-01, -2.26093368e-01],
       [-7.89466782e-01, -2.26093368e-01],
       [-6.44465993e-01, -2.26093368e-01],
       [-7.71822042e-02,  1.10220517e+00],
       [-8.65999486e-04, -2.26093368e-01],
       [-1.40779041e-01, -2.26093368e-01],
       [ 3.15099326e+00,  2.43050370e+00],
       [-9.31923697e-01, -2.26093368e-01],
       [ 3.80715024e-01,  1.10220517e+00],
       [-8.65782986e-01, -1.55439190e+00],
       [-9.72625673e-01, -2.26093368e-01],
       [ 7.73743478e-01,  1.10220517e+00],
       [ 1.31050078e+00,  1.10220517e+00],
       [-2.97227261e-01, -2.26093368e-01],
       [-1.43322915e-01, -1.55439190e+00],
       [-5.04552951e-01, -2.26093368e-01],
       [-4.91995958e-02,  1.10220517e+00],
       [ 2.40309445e+00, -2.26093368e-01],
       [-1.14560907e+00, -2.26093368e-01],
       [-6.90255715e-01, -2.26093368e-01],
       [ 6.68172729e-01, -2.26093368e-01],
       [ 2.53521350e-01, -2.26093368e-01],
       [ 8.09357707e-01, -2.26093368e-01],
       [-2.05647815e-01, -1.55439190e+00],
       [-1.27280274e+00, -2.88269044e+00],
       [ 5.00114703e-02,  1.10220517e+00],
       [ 1.44532608e+00, -2.26093368e-01],
       [-2.41262044e-01,  1.10220517e+00],
       [-7.16966387e-01, -2.26093368e-01],
       [-9.68809863e-01, -2.26093368e-01],
       [ 1.67029651e-01,  1.10220517e+00],
       [ 2.81647389e+00,  1.10220517e+00],
       [ 2.05187753e-01,  1.10220517e+00],
       [-4.28236746e-01, -1.55439190e+00],
       [ 3.01854946e-01, -2.26093368e-01],
       [ 7.20322135e-01,  1.10220517e+00],
       [-1.01841540e+00, -2.26093368e-01],
       [-1.46104938e+00, -1.55439190e+00],
       [-1.89112638e-01,  1.10220517e+00],
       [-1.01459959e+00, -2.26093368e-01]])

In [ ]:
theta_array = np.zeros((3,1))

In [ ]:
#linear regression
def hypothesis(theta_array,x1,x2):
  return theta_array[0]+theta_array[1]*x1 +theta_array[2]*x2

def cost_funtion(theta_array,x1,x2,y,m):
  sum=0
  for i in range(m):
    sum=sum+((theta_array[0]+theta_array[1]*x1[i]+theta_array[2]*x2[i])-y[i])*2

  return sum/(2*m)

def gradiant_descent(theta_array,x1,x2,y,m,alpha):
  summation_0=0
  summation_1=0
  summation_2=0
  for i in range(m):
    summation_0=summation_0+((theta_array[0]+theta_array[1]*x1[i]+theta_array[2]*x2[i])-y[i])
    summation_1=summation_1+x1[i]*((theta_array[0]+theta_array[1]*x1[i]+theta_array[2]*x2[i])-y[i])
    summation_2=summation_2+x2[i]*((theta_array[0]+theta_array[1]*x1[i]+theta_array[2]*x2[i])-y[i])
  new_theta0=theta_array[0]-(alpha/m)*summation_0
  new_theta1=theta_array[1]-(alpha/m)*summation_1
  new_theta2=theta_array[2]-(alpha/m)*summation_2
  updated_new_theta=[new_theta0,new_theta1,new_theta2]
  return updated_new_theta

def training(x1,x2,y,alpha,iters,theta_array,m):

  cost_values=[]

  for i in range(iters):
    theta_array=gradiant_descent(theta_array,x1,x2,y,m,alpha)
    cost_values.append(cost_funtion(theta_array,x1,x2,y,m))

  return cost_values,theta_array

In [ ]:
alpha = 0.0001
iters = 50
cost_val, theta_aray = training(x2_norm[:,0:2], x2_norm[:,1:2], y2, alpha, iters, theta_array, m)

In [ ]:
plt.plot(x_axis, cost_val)
plt